version: '2'

services:
  virtualizationlayer:
    networks:
      - backend
      - frontend
    environment:
      - MQTT_BROKER_URL=mqtt://mosquitto/
      - VL_PUBLIC_URL=http://localhost/
      - DFM_URL=http://datafusionmanager:8319/
      - SCRAL_URL=http://scral:8080/scral/
      - RESOURCE_CATALOGUE_URL=http://resourcecatalogue:44441/
      - INSTANCE_NAME=DEVELOPER
      - LOG_LEVEL=verbose
    volumes:
    - ../Virtualizationlayer:/opt/prs/app

