version: '2'
services:
  amdb:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: keypass
    volumes:
      - ./volumes/am/db/:/docker-entrypoint-initdb.d:ro
    logging:
      driver: json-file
      options:
         max-size: "1g"
         max-file: "5"
    networks:
      - am_subnet

  ampap:
    image: almanacproject/keypasspap
    restart: unless-stopped
    command: ["/opt/keypass/start"]
    entrypoint: ["/opt/keypass/wait-for-it.sh", "amdb:3306", "--"]
    depends_on:
      - amdb
    volumes:
      - ./volumes/am/pap/:/opt/keypass/conf:ro
    logging:
      driver: json-file
      options:
         max-size: "1g"
         max-file: "5"
    networks:
      - almanacproject_backend
      - am_subnet

  ampdp:
    image: almanacproject/keypasspdp
    restart: unless-stopped
    command: ["/opt/keypass/start"]
    entrypoint: ["/opt/keypass/wait-for-it.sh", "amdb:3306", "--"]
    depends_on:
      - amdb
    volumes:
      - ./volumes/am/pdp/:/opt/keypass/conf:ro
    logging:
      driver: json-file
      options:
         max-size: "1g"
         max-file: "5"
    networks:
      - almanacproject_backend
      - am_subnet
networks:
  almanacproject_backend:
    external: true
  am_subnet:
    driver: bridge
