version: '2'

services:
  virtualizationlayer:
    restart: unless-stopped
    image: almanacproject/virtualizationlayer:latest
    ports:
      - "80:80"
    environment:
      - MQTT_BROKER_URL=mqtt://mosquitto/
      - VL_PUBLIC_URL=http://almanac-lab.alexandra.dk/
      - DFM_URL=http://datafusionmanager:8319/
      - SCRAL_URL=http://scral:8080/scral/
      - RESOURCE_CATALOGUE_URL=http://resourcecatalogue:44441/
      - INSTANCE_NAME=ALMANAC-LAB
      - LOG_LEVEL=verbose
    networks:
      - almanacproject_backend
networks:
  almanacproject_backend:
    external: true
