version: '2'

services:
  mosquitto:
    image: ansi/mosquitto
    ports:
      - "1883:1883"
    networks:
      - backend
  virtualizationlayer:
    image: almanacproject/virtualizationlayer:latest
    ports:
      - "80:80"
    networks:
      - backend
      - frontend
    environment:
      - MQTT_BROKER_URL=mqtt://mosquitto/
      - VL_PUBLIC_URL=http://almanac-lab.alexandra.dk/
      - DFM_URL=http://datafusionmanager:8319/
      - SCRAL_URL=http://scral:8080/scral/
      - RESOURCE_CATALOGUE_URL=http://resourcecatalogue:44441/
      - INSTANCE_NAME=ALMANAC-LAB
      - LOG_LEVEL=verbose

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
