mosquitto:
  image: ansi/mosquitto
  ports:
    - "1883:1883"
datafusionmanager:
  image: glagnar/datafusionmanager:latest
  links:
    - mosquitto
  ports:
    - "8319:8319"
  volumes:
    - /almanac/dfm:/config
virtualizationlayer:
  image: glagnar/virtualizationlayer:latest
  links:
    - mosquitto
    - datafusionmanager
  ports:
    - "8080:80"
  environment:
    - MQTT_BROKER_URL=mqtt://mosquitto
    - VL_PUBLIC_URL=http://almanac-lab.alexandra.dk
    - DFM_URL=http://datafusionmanager:8319
