mosquitto:
  image: ansi/mosquitto
  ports:
    - "1883:1883"
datafusionmanager:
  image: glagnar/datafusionmanager:latest
  links:
    - mosquitto
  ports:
    - "8319:8319"
  volumes:
    - /almanac/dfm/config:/config
scral:
  image: glagnar/scral:latest
  links:
    - mosquitto
  ports:
    - "8081:8080"
  volumes:
    - /almanac/scral/config:/config
resourcecatalogue:
  image: glagnar/resourcecatalogue:latest
  ports:
    - "44441:44441"
  links:
    - mosquitto
  volumes:
    - /almanac/resourcecatalogue/data:/opt/IoTResourceCatalogue/ResourceDB
    - /almanac/resourcecatalogue/config:/config
virtualizationlayer:
  image: glagnar/virtualizationlayer:latest
  links:
    - mosquitto
    - datafusionmanager
    - resourcecatalogue
    - scral
  ports:
    - "80:80"
  environment:
    - MQTT_BROKER_URL=mqtt://mosquitto/
    - VL_PUBLIC_URL=http://almanac-lab.alexandra.dk/
    - DFM_URL=http://datafusionmanager:8319/
    - SCRAL_URL=http://scral:8081/scral/
    - RESOURCE_CATALOGUE_URL=http://resourcecatalogue:44441/
    - INSTANCE_NAME=ALMANAC-LAB
    - LOG_LEVEL=verbose
