mosquitto:
  image: ansi/mosquitto
  ports:
    - "1883:1883"
datafusionmanager:
  image: almanacproject/datafusionmanager:latest
  links:
    - mosquitto
  ports:
    - "8319:8319"
scral:
  image: almanacproject/scral:latest
  links:
    - mosquitto
  ports:
    - "8081:8080"
resourcecatalogue:
  image: almanacproject/resourcecatalogue:latest
  ports:
    - "44441:44441"
  links:
    - mosquitto
virtualizationlayer:
  image: almanacproject/virtualizationlayer:latest
  links:
    - mosquitto
    - datafusionmanager
    - resourcecatalogue
    - scral
  ports:
    - "80:80"
  environment:
    - MQTT_BROKER_URL=mqtt://mosquitto/
    - VL_PUBLIC_URL=http://almanac-lab.alexandra.dk/
    - DFM_URL=http://datafusionmanager:8319/
    - SCRAL_URL=http://scral:8080/scral/
    - RESOURCE_CATALOGUE_URL=http://resourcecatalogue:44441/
    - INSTANCE_NAME=ALMANAC-LAB
    - LOG_LEVEL=verbose
