mosquitto:
  image: ansi/mosquitto
  ports:
    - "1883:1883"
datafusionmanager:
  image: glagnar/datafusionmanager:latest
  links:
    - mosquitto
  ports:
    - "8319:8319"
  volumes:
    - /almanac/dfm:/config
scral:
  image: glagnar/scral:latest
  links:
    - mosquitto
  ports:
    - "8080:8080"
  volumes:
    - /almanac/scral/applicationContext-pwal.xml:/usr/local/tomcat/webapps/scral/WEB-INF/classes/applicationContext-pwal.xml
resourcecatalogue:
  image: glagnar/resourcecatalogue:latest
  ports:
    - "44441:44441"
  links:
    - mosquitto
  volumes:
    - /almanac/resourcecatalogue/ResourceDB:/opt/IoTResourceCatalogue/ResourceDB
    - /almanac/resourcecatalogue/ALMANAC-LAB.config:/opt/IoTResourceCatalogue/IoTResourceCatalogue.exe.config
virtualizationlayer:
  image: glagnar/virtualizationlayer:latest
  links:
    - mosquitto
    - datafusionmanager
    - resourcecatalogue
    - scral
  ports:
    - "80:80"
  environment:
    - MQTT_BROKER_URL=mqtt://mosquitto
    - VL_PUBLIC_URL=http://almanac-lab.alexandra.dk
    - DFM_URL=http://datafusionmanager:8319
    - SCRAL_URL=http://scral:8080/scral
    - RESOURCE_CATALOGUE_URL=http://resourcecatalogue:44441
    - INSTANCE_NAME=ALMANAC-LAB
