version: '2'

services:
  virtualizationlayer:
    ports:
      - "8082:80"
    logging:
      driver: json-file
      options:
         max-size: "1g"
         max-file: "5"
    environment:
      STORAGE_MANAGER_URL: http://ngix-queryapi/
      REQUIRE_AUTHORIZATION: 'no'
      REQUIRE_POLICY: 'no'
      OPENID_PUBLIC_KEY: |-
          -----BEGIN PUBLIC KEY-----
          MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDdlatRjRjogo3WojgGHFHYLugdUWAY9iR3fy4arWNA1KoS8kVw33cJibXr8bvwUAUparCwlvdbH6dvEOfou0/gCFQsHUfQrSDv+MuSUMAe8jzKE4qW+jK+xQU9a03GUnKHkkle+Q0pX/g6jXZ7r1/xAK5Do2kQ+X5xK9cipRgEKwIDAQAB
          -----END PUBLIC KEY-----

